pipeline {
	agent {
		label 'ubuntu-vm'
		}
	stages { 
		stage('Checkout') {
			steps{
			     checkout scm
			     
			     sh 'git submodule update --init --recursive'
                             }
		stage('Update Python Modules') {
		sh 'virtual env && source env/bin/activate && pip install --upgrage -r requirements.txt'
		}

		stage('Test') {
		sh 'source env/bin/activate && python ./manage.py runserver'
		}
